name: chat_io
description: A sample command-line application for chat with tcp socket in local network.
version: 0.0.2
repository: https://github.com/P-B1101/console-chat

environment:
  sdk: ^3.4.1

dependencies:
  args: ^2.4.2
  mime: ^1.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
